/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.56
 * Generated at: 2016-01-16 01:54:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.Locale;
import java.util.Enumeration;
import java.util.regex.Pattern;
import java.net.URLEncoder;
import com.vmware.vise.util.StringUtil;
import com.vmware.vise.util.i18n.ResourceUtil;

public final class ui_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;



   // Defines the IE document capability
   response.setHeader("X-UA-Compatible", "IE=edge");

   // Force same origin to prevent click-jacking attacks with an iframe
   response.setHeader("X-Frame-Options", "SAMEORIGIN");

   // Disables caching
   response.setHeader("Cache-Control", "no-cache, no-store, must-revalidate");
   response.setHeader("Pragma", "no-cache");
   response.setDateHeader("Expires", 0);

   String wmode = "window"; // default
   Boolean accessible = (Boolean) session.getAttribute("accessible");
   // wmode value of 'opaque' or 'transparent' may cause the Flash movie to
   // be invisible to assistive technologies such as a screen reader.
   if (accessible != null && ! accessible) {
      wmode = "opaque";
   }

   Locale locale = (Locale) session.getAttribute("applicationLocale");
   String encodedLocale = URLEncoder.encode(locale == null ? "" : locale.toString());
   StringBuffer flashvars = new StringBuffer("locale=").append(encodedLocale);

   String localeChain = ResourceUtil.getVerifiedAppLocale(request).toString();
   String encodedLocaleChain = URLEncoder.encode(localeChain);
   String resourceModule = "locales/UI-" + encodedLocaleChain + ".swf";

   // Includes the resource module only if it exists
   if (application.getRealPath(resourceModule) != null) {
      flashvars.append("&amp;").append("localeChain=").append(encodedLocaleChain);
      flashvars.append("&amp;").append("resourceModuleURLs=").append(resourceModule);
   }

   Enumeration<String> names = request.getParameterNames();

   while(names.hasMoreElements()) {
      String name = names.nextElement();
      String value = request.getParameter(name);
      if ("locale".equals(name)) {
         // Prevent the duplication of the locale param.
         continue;
      }
      // URL Encoding is needed to fix bug # 1001328
      String encodedName = URLEncoder.encode(name);
      String encodedValue = URLEncoder.encode(value);
      flashvars.append("&amp;").append(encodedName).append("=").append(encodedValue);
   }

   String swf = "UI";
   boolean debugBuild = !"false".equals("false");
   if (!debugBuild && "true".equals(request.getParameter("debug"))) {
      swf += "-debug";
   }

   String missingFlashMessage = "${missingFlashMessage}";
   // When the template variable is not passed, the ${.. token will not be
   // replaced, hence doing the following check.
   if (missingFlashMessage.startsWith("${")) {
      missingFlashMessage = "";
   } else {
      missingFlashMessage = "<p>" + missingFlashMessage + "</p>";
   }


      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");
      out.write("<!-- saved from url=(0014)about:internet -->\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\" lang=\"en\" xml:lang=\"en\">\r\n");
      out.write("   <head>\r\n");
      out.write("      <title>vSphere Web Client on Linux</title>\r\n");
      out.write("      <meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("      <style type=\"text/css\" media=\"screen\">\r\n");
      out.write("         html, body {\r\n");
      out.write("            height: 100%;\r\n");
      out.write("            overflow: auto;\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            padding: 0;\r\n");
      out.write("            font: 13px Arial, 'Helvetica Neue', sans-serif;\r\n");
      out.write("         }\r\n");
      out.write("         p {\r\n");
      out.write("            margin: 20px;\r\n");
      out.write("            padding: 0;\r\n");
      out.write("         }\r\n");
      out.write("         img {\r\n");
      out.write("            border: 0;\r\n");
      out.write("         }\r\n");
      out.write("         #flashContent {\r\n");
      out.write("            display: none;\r\n");
      out.write("         }\r\n");
      out.write("         #container_app {\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            top: 0;\r\n");
      out.write("            left: 0;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height: 100%;\r\n");
      out.write("            outline: none;\r\n");
      out.write("         }\r\n");
      out.write("\t#cus-menu {\r\n");
      out.write("\t\tposition: absolute;\r\n");
      out.write("\t\tleft: 0;\r\n");
      out.write("\t\ttop: 50%;\r\n");
      out.write("\t\twidth: 5px;\r\n");
      out.write("\t\theight: 50px;\r\n");
      out.write("\t\tbackground-color: #fff;\r\n");
      out.write("\t\tz-index: 999;\r\n");
      out.write("\t\tcursor: pointer;\r\n");
      out.write("\t\tborder-radius: 0px 4px 4px 0px;\r\n");
      out.write("\t}\r\n");
      out.write("      </style>\r\n");
      out.write("      <link type=\"text/css\" href=\"history/history.css\" rel=\"stylesheet\" />\r\n");
      out.write("      <link rel=\"stylesheet\" type=\"text/css\" href=\"assets/pull-menu/css/jPushMenu.css\" />\r\n");
      out.write("      <link type=\"image/x-icon\" href=\"assets/application.ico\" rel=\"shortcut icon\"/>\r\n");
      out.write("      <script type=\"text/javascript\" src=\"history/history.js\"></script>\r\n");
      out.write("      <script type=\"text/javascript\" src=\"assets/swfobject.js\"></script>\r\n");
      out.write("      <script type=\"text/javascript\" src=\"assets/jquery.min.js\"></script>\r\n");
      out.write("      <script type=\"text/javascript\" src=\"assets/jquery.scrollbars.js\"></script>\r\n");
      out.write("      <script type=\"text/javascript\" src=\"assets/angular.min.js\"></script>\r\n");
      out.write("      <script type=\"text/javascript\" src=\"assets/ng-grid-2.0.7.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("      <!-- custom menu -->\r\n");
      out.write("      <script type=\"text/javascript\" src=\"assets/pull-menu/js/jPushMenu.js\"></script>\r\n");
      out.write("      <script>\r\n");
      out.write("\tjQuery(document).ready(function($) {\r\n");
      out.write("\t$('.toggle-menu').jPushMenu();\r\n");
      out.write("\t});\r\n");
      out.write("      </script>\r\n");
      out.write("      ");
 // TODO mthirunavukkar inject this from flex at the end of Code Complete 
      out.write("\r\n");
      out.write("      <script type=\"text/javascript\" src=\"ovf-ui/assets/scripts/ovfWizardInitializer.js\"></script>\r\n");
      out.write("      <script type=\"text/javascript\">\r\n");
      out.write("      //<![CDATA[\r\n");
      out.write("         swfobject.embedSWF(\r\n");
      out.write("            '");
      out.print( swf );
      out.write(".swf',\r\n");
      out.write("            'flashContent',\r\n");
      out.write("            '100%',\r\n");
      out.write("            '100%',\r\n");
      out.write("            '11.5.0',\r\n");
      out.write("            'playerProductInstall.swf',\r\n");
      out.write("             false, {\r\n");
      out.write("               quality: 'high',\r\n");
      out.write("               bgcolor: '#ffffff',\r\n");
      out.write("               allowscriptaccess: 'sameDomain',\r\n");
      out.write("               allowfullscreen: 'true',\r\n");
      out.write("               menu: false,\r\n");
      out.write("               flashvars: '");
      out.print( flashvars.toString().replaceAll("&amp;", "&") );
      out.write("',\r\n");
      out.write("               scale: 'noscale',\r\n");
      out.write("               wmode: '");
      out.print( wmode );
      out.write("'\r\n");
      out.write("            }, {\r\n");
      out.write("               id: 'container_app',\r\n");
      out.write("               name: 'container_app',\r\n");
      out.write("               align: 'middle'\r\n");
      out.write("            });\r\n");
      out.write("         swfobject.createCSS('#flashContent', 'display: block; text-align: left;');\r\n");
      out.write("         $.scrollbars({\r\n");
      out.write("            swfId: '#container_app'\r\n");
      out.write("         });\r\n");
      out.write("      //]]>\r\n");
      out.write("      </script>\r\n");
      out.write("   </head>\r\n");
      out.write("   <body>\r\n");
      out.write("      <div id=\"container\"></div>\r\n");
      out.write("      <div id=\"flashContent\">\r\n");
      out.write("         <p>\r\n");
      out.write("            To view this page ensure that Adobe Flash Player version\r\n");
      out.write("            11.5.0 or greater is installed.\r\n");
      out.write("         </p>\r\n");
      out.write("         <p>\r\n");
      out.write("            <a href=\"http://www.adobe.com/go/getflashplayer\">\r\n");
      out.write("               <img src=\"assets/getFlashPlayer.gif\" alt=\"Get Adobe Flash Player\" />\r\n");
      out.write("            </a>\r\n");
      out.write("         </p>");
      out.print( missingFlashMessage );
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("      <noscript>\r\n");
      out.write("         <object classid=\"clsid:D27CDB6E-AE6D-11cf-96B8-444553540000\" width=\"100%\" height=\"100%\" id=\"container_app\">\r\n");
      out.write("            <param name=\"movie\" value=\"");
      out.print(swf);
      out.write(".swf\" />\r\n");
      out.write("            <param name=\"flashvars\" value=\"");
      out.print( flashvars );
      out.write("\"/>\r\n");
      out.write("            <param name=\"quality\" value=\"high\" />\r\n");
      out.write("            <param name=\"bgcolor\" value=\"#ffffff\" />\r\n");
      out.write("            <param name=\"allowScriptAccess\" value=\"sameDomain\" />\r\n");
      out.write("            <param name=\"allowFullScreen\" value=\"true\" />\r\n");
      out.write("            <!--[if !IE]>-->\r\n");
      out.write("            <object type=\"application/x-shockwave-flash\" data=\"");
      out.print(swf);
      out.write(".swf\" width=\"100%\" height=\"100%\">\r\n");
      out.write("               <param name=\"flashvars\" value=\"");
      out.print( flashvars );
      out.write("\"/>\r\n");
      out.write("               <param name=\"quality\" value=\"high\" />\r\n");
      out.write("               <param name=\"bgcolor\" value=\"#ffffff\" />\r\n");
      out.write("               <param name=\"allowScriptAccess\" value=\"sameDomain\" />\r\n");
      out.write("               <param name=\"allowFullScreen\" value=\"true\" />\r\n");
      out.write("            <!--<![endif]-->\r\n");
      out.write("            <!--[if gte IE 6]>-->\r\n");
      out.write("               <p>\r\n");
      out.write("                  Either scripts and active content are not permitted to run or Adobe Flash Player version\r\n");
      out.write("                  11.5.0 or greater is not installed.\r\n");
      out.write("               </p>\r\n");
      out.write("            <!--<![endif]-->\r\n");
      out.write("               <p>\r\n");
      out.write("                   <a href=\"http://www.adobe.com/go/getflashplayer\">\r\n");
      out.write("                      <img src=\"assets/getFlashPlayer.gif\" alt=\"Get Adobe Flash Player\" />\r\n");
      out.write("                   </a>\r\n");
      out.write("               </p>\r\n");
      out.write("            <!--[if !IE]>-->\r\n");
      out.write("            </object>\r\n");
      out.write("            <!--<![endif]-->\r\n");
      out.write("         </object>\r\n");
      out.write("      </noscript>\r\n");
      out.write("   </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
